server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

mybatis:
  # 配置mapper xml文件位置
  mapper-locations: classpath*:/mapper/*Mapping.xml
  # 配置映射类所在包名
  type-aliases-package: com.example.bbs.model
  configuration:
    map-underscore-to-camel-case: true