server:
  port: 80

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

mybatis:
  mapper-locations: classpath:..\main\java\com\example\bbs\model\mapping\*Mapping.xml